baseURL = 'https://ogabriel.me/'
copyright = "{year}"
languageCode = 'en-US'
defaultContentLanguage = 'pt'
theme = 'lowkey'
title = 'Gabriel Messias'
enableRobotsTXT = true
summaryLength = 15
paginate = 5


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
